spring.jpa.database-platform=org.hibernate.community.dialect.Oracle12cDialect
#oracle.jdbc.fanEnabled=false
##this is not used when deployed in kubernetes. Just for local testing
#spring.datasource.url=jdbc:oracle:thin:@practice_medium
#spring.datasource.oracleucp.connection-properties.oracle.net.tns_admin=C:/Users/ianle/Desktop/Proyecto/oci_devops_project/MtdrSpring/backend/wallet
#spring.datasource.username=EQUIPO82
#spring.datasource.password=Asashin128*
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

##Properties of UCP
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.sql-for-validate-connection=select * from dual
spring.datasource.oracleucp.connection-pool-name=connectionPoolName1
spring.datasource.oracleucp.initial-pool-size=15
spring.datasource.oracleucp.min-pool-size=10
spring.datasource.oracleucp.max-pool-size=30

##Logging properties for UCP
logging.level.root=trace
logging.file.name=logs.log
logging.level.oracle.ucp=trace
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type=TRACE

deepseek.api.key=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
deepseek.api.url=https://api.groq.com/openai/v1/chat/completions

#spring.security.user.name=psong
#spring.security.user.password=WELcome__12345

telegram.bot.token=8281877672:AAH_0hF0Y3mDhl3KXtPluMkWIBNGpd8C0eA
telegram.bot.name=IFLH_bot


